### ISSUE TITLE
Ability to include custom modules during upload

### ISSUE THREAD

**Issue by Goggin** [morgen-so/morgen-cw-sdk#6]
https://github.com/morgen-so/morgen-cw-sdk/blob/main/src/index.ts#L92-L116

I think being able to accept "extra=" in the upload function, and adding to this list would allow for flexibility of reusable and sharable code.

I am willing to make a PR for this.

**Comment by lukebarnard1** [comment]
I can certainly see the advantage of user-specified utility functions supported by the SDK, and thanks for offering to make a PR - that would be _very_ appreciated. 🥳 

In terms of the implementation, I think a parameter here makes sense, and I think we should follow the pattern of having an `options` parameter with TypeScript documented fields, so in this case:

```
async upload(options:{ 
    /** something **/
    userUtilityFunctions: Function[]
   }) { ... }
``` 

And then the array can be union-ed with a default array of functions. 

The specified functions can't access anything global or imported (unless it's taken from the `sandbox` import). In the workflow script they can be imported and used as any other import (I think). This should probably be mentioned in the docs.

Wdyt? 😄

**Comment by Goggin** [comment]
That is pretty much what I had in mind.
